# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Zatourie
tagline:             Zatourie Study Wiki
url:                 http://zatourie.github.io/wiki/
paginate:            1
baseurl:             http://zatourie.github.io/wiki/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              mango
  url:               
  email:             minkyu.shim@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/zatourie/wiki/
